version: '3.7'
services:
  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091:8091"  # Web Console
      - "8092:8092"  # Query
      - "8093:8093"  # Index
      - "8094:8094"  # Full-Text Search
      - "11210:11210" # Data
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=admin123
    networks:
      - couchbase_network
networks:
  couchbase_network:
    driver: bridge