version: '3.7'
services:

  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091:8091"  # Web Console
      - "8092:8092"  # Query
      - "8093:8093"  # Index
      - "8094:8094"  # Full-Text Search
      - "11210:11210" # Data
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=admin123
    networks:
      - couchbase_network

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - "8180:8080"  # Web Console
    volumes:
      - ./src/test/wiremock/extensions:/var/wiremock/extensions
      - ./src/test/wiremock/__files:/home/wiremock/__files
      - ./src/test/wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]      
    networks:
      - couchbase_network

networks:
  couchbase_network:
    driver: bridge